version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: beer_partner

networks:
  mongodb:
    name: mongodb