# stack-beer-partner-iam

AWSTemplateFormatVersion: 2010-09-09
Description: IAM role

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: role-beer-partner-lambda
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: policy-lambda-dynamodb
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: 
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                Resource: 
                  - arn:aws:dynamodb:us-east-1:546063609182:table/prd_beer_partner

Outputs:
  LambdaRoleArn:
    Description: LambdaRole
    Value: !GetAtt LambdaRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'
