# stack-beer-partner-api-gateway

AWSTemplateFormatVersion: 2010-09-09
Description: "API Gateway"

Resources:
  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: api-beer-partner
      EndpointConfiguration:
        Types:
          - PRIVATE

  APIGatewayResourceRoot:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGateway
      ParentId: !GetAtt APIGateway.RootResourceId
      PathPart: api

  APIGatewayResourcePartner:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref APIGateway
      ParentId: !Ref APIGatewayResourceRoot
      PathPart: partner

Outputs:
  APIGateway:
    Description: API Gateway
    Value: !Ref APIGateway
    Export:
      Name: !Sub '${AWS::StackName}-APIGateway'

  APIGatewayResourceRoot:
    Description: Resource API
    Value: !Ref APIGatewayResourceRoot
    Export:
      Name: !Sub '${AWS::StackName}-ResourceRoot'

  APIGatewayResourcePartner:
    Description: Resource Partner
    Value: !Ref APIGatewayResourcePartner
    Export:
      Name: !Sub '${AWS::StackName}-ResourcePartner'